version: '3.7'

services:
  app:
    image: mzayas/node-started:2-mysql
    ports:
      - 8001:8080
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: chat-app
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./chat-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat-app
    